"""init

Revision ID: 7bad0f1d7070
Revises: 
Create Date: 2026-03-04 21:19:25.432605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bad0f1d7070'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pokemon_pkey'))
    )
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=True)
    op.create_index(op.f('ix_pokemon_id'), 'pokemon', ['id'], unique=False)
    # ### end Alembic commands ###
