"""init_cache

Revision ID: a6c86641a377
Revises: 
Create Date: 2026-03-05 18:53:44.365091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6c86641a377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_ability_name'), 'cached_ability', ['name'], unique=True)
    op.create_table('cached_evolution_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cached_move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_move_name'), 'cached_move', ['name'], unique=True)
    op.create_table('cached_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_pokemon_name'), 'cached_pokemon', ['name'], unique=True)
    op.create_table('cached_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_species_name'), 'cached_species', ['name'], unique=True)
    op.create_table('cached_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_type_name'), 'cached_type', ['name'], unique=True)
    op.create_table('seed_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_progress')
    op.drop_index(op.f('ix_cached_type_name'), table_name='cached_type')
    op.drop_table('cached_type')
    op.drop_index(op.f('ix_cached_species_name'), table_name='cached_species')
    op.drop_table('cached_species')
    op.drop_index(op.f('ix_cached_pokemon_name'), table_name='cached_pokemon')
    op.drop_table('cached_pokemon')
    op.drop_index(op.f('ix_cached_move_name'), table_name='cached_move')
    op.drop_table('cached_move')
    op.drop_table('cached_evolution_chain')
    op.drop_index(op.f('ix_cached_ability_name'), table_name='cached_ability')
    op.drop_table('cached_ability')
    # ### end Alembic commands ###
